services:
  app:
    build: .
    image: firefly-iii:local
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: sqlite
      DB_HOST: ""
      DB_PORT: ""
      DB_DATABASE: ""
      DB_USERNAME: ""
      DB_PASSWORD: ""
      TRUSTED_PROXIES: "**"
    volumes:
      - ./storage/database:/var/www/html/storage/database
      - ./storage/upload:/var/www/html/storage/upload
    ports:
      - "8080:8080"
    networks:
      - firefly_iii

  cron:
    image: alpine
    restart: unless-stopped
    container_name: firefly_iii_cron
    env_file: .env
    command: ["sh", "-c", "apk add --no-cache tzdata wget && (ln -sf /usr/share/zoneinfo/$$TZ /etc/localtime || true) && echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\" | crontab - && crond -f -L /dev/stdout"]
    networks:
      - firefly_iii
    depends_on:
      - app

networks:
  firefly_iii:
    driver: bridge
